import { Inter } from 'next/font/google'
import './globals.css'
import Navigation from './Components/Navigation'
import Trending from './Components/Trending'
import CreateBtn from './Components/CreateBtn'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sociyo Media',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-socialBg`}>
        <div className="flex mx-16 my-5 gap-10">
          <Navigation />
          {children}
          <Trending />
          <CreateBtn />
        </div>
      </body>
    </html>
  )
}
